# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rungrid.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'rungrid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrungrid.proto\x12\nrungrid.v1\"\x99\x01\n\x07Request\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tworker_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x12\n\nattempt_id\x18\x04 \x01(\t\x12\x13\n\x0blease_token\x18\x05 \x01(\t\x12\x14\n\x0cpayload_json\x18\x06 \x01(\x0c\x12\x14\n\x0cwait_seconds\x18\x07 \x01(\x05\" \n\x08Response\x12\x14\n\x0cpayload_json\x18\x01 \x01(\x0c\x32\xe7\x03\n\rWorkerService\x12;\n\x0eRegisterWorker\x12\x13.rungrid.v1.Request\x1a\x14.rungrid.v1.Response\x12\x35\n\x08LeaseJob\x12\x13.rungrid.v1.Request\x1a\x14.rungrid.v1.Response\x12\x39\n\x0cStartAttempt\x12\x13.rungrid.v1.Request\x1a\x14.rungrid.v1.Response\x12\x36\n\tHeartbeat\x12\x13.rungrid.v1.Request\x1a\x14.rungrid.v1.Response\x12;\n\x0eReportProgress\x12\x13.rungrid.v1.Request\x1a\x14.rungrid.v1.Response\x12<\n\x0f\x43ompleteAttempt\x12\x13.rungrid.v1.Request\x1a\x14.rungrid.v1.Response\x12\x38\n\x0b\x46\x61ilAttempt\x12\x13.rungrid.v1.Request\x1a\x14.rungrid.v1.Response\x12:\n\rReleaseWorker\x12\x13.rungrid.v1.Request\x1a\x14.rungrid.v1.ResponseB8Z6github.com/ZubairQazi/rungrid/gen/rungrid/v1;rungridv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rungrid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/ZubairQazi/rungrid/gen/rungrid/v1;rungridv1'
  _globals['_REQUEST']._serialized_start=30
  _globals['_REQUEST']._serialized_end=183
  _globals['_RESPONSE']._serialized_start=185
  _globals['_RESPONSE']._serialized_end=217
  _globals['_WORKERSERVICE']._serialized_start=220
  _globals['_WORKERSERVICE']._serialized_end=707
# @@protoc_insertion_point(module_scope)
