# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rungrid_pb2 as rungrid__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rungrid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/rungrid.v1.WorkerService/RegisterWorker',
                request_serializer=rungrid__pb2.Request.SerializeToString,
                response_deserializer=rungrid__pb2.Response.FromString,
                _registered_method=True)
        self.LeaseJob = channel.unary_unary(
                '/rungrid.v1.WorkerService/LeaseJob',
                request_serializer=rungrid__pb2.Request.SerializeToString,
                response_deserializer=rungrid__pb2.Response.FromString,
                _registered_method=True)
        self.StartAttempt = channel.unary_unary(
                '/rungrid.v1.WorkerService/StartAttempt',
                request_serializer=rungrid__pb2.Request.SerializeToString,
                response_deserializer=rungrid__pb2.Response.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/rungrid.v1.WorkerService/Heartbeat',
                request_serializer=rungrid__pb2.Request.SerializeToString,
                response_deserializer=rungrid__pb2.Response.FromString,
                _registered_method=True)
        self.ReportProgress = channel.unary_unary(
                '/rungrid.v1.WorkerService/ReportProgress',
                request_serializer=rungrid__pb2.Request.SerializeToString,
                response_deserializer=rungrid__pb2.Response.FromString,
                _registered_method=True)
        self.CompleteAttempt = channel.unary_unary(
                '/rungrid.v1.WorkerService/CompleteAttempt',
                request_serializer=rungrid__pb2.Request.SerializeToString,
                response_deserializer=rungrid__pb2.Response.FromString,
                _registered_method=True)
        self.FailAttempt = channel.unary_unary(
                '/rungrid.v1.WorkerService/FailAttempt',
                request_serializer=rungrid__pb2.Request.SerializeToString,
                response_deserializer=rungrid__pb2.Response.FromString,
                _registered_method=True)
        self.ReleaseWorker = channel.unary_unary(
                '/rungrid.v1.WorkerService/ReleaseWorker',
                request_serializer=rungrid__pb2.Request.SerializeToString,
                response_deserializer=rungrid__pb2.Response.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaseJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAttempt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteAttempt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailAttempt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=rungrid__pb2.Request.FromString,
                    response_serializer=rungrid__pb2.Response.SerializeToString,
            ),
            'LeaseJob': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaseJob,
                    request_deserializer=rungrid__pb2.Request.FromString,
                    response_serializer=rungrid__pb2.Response.SerializeToString,
            ),
            'StartAttempt': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAttempt,
                    request_deserializer=rungrid__pb2.Request.FromString,
                    response_serializer=rungrid__pb2.Response.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=rungrid__pb2.Request.FromString,
                    response_serializer=rungrid__pb2.Response.SerializeToString,
            ),
            'ReportProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProgress,
                    request_deserializer=rungrid__pb2.Request.FromString,
                    response_serializer=rungrid__pb2.Response.SerializeToString,
            ),
            'CompleteAttempt': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteAttempt,
                    request_deserializer=rungrid__pb2.Request.FromString,
                    response_serializer=rungrid__pb2.Response.SerializeToString,
            ),
            'FailAttempt': grpc.unary_unary_rpc_method_handler(
                    servicer.FailAttempt,
                    request_deserializer=rungrid__pb2.Request.FromString,
                    response_serializer=rungrid__pb2.Response.SerializeToString,
            ),
            'ReleaseWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseWorker,
                    request_deserializer=rungrid__pb2.Request.FromString,
                    response_serializer=rungrid__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rungrid.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rungrid.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rungrid.v1.WorkerService/RegisterWorker',
            rungrid__pb2.Request.SerializeToString,
            rungrid__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaseJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rungrid.v1.WorkerService/LeaseJob',
            rungrid__pb2.Request.SerializeToString,
            rungrid__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartAttempt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rungrid.v1.WorkerService/StartAttempt',
            rungrid__pb2.Request.SerializeToString,
            rungrid__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rungrid.v1.WorkerService/Heartbeat',
            rungrid__pb2.Request.SerializeToString,
            rungrid__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rungrid.v1.WorkerService/ReportProgress',
            rungrid__pb2.Request.SerializeToString,
            rungrid__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteAttempt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rungrid.v1.WorkerService/CompleteAttempt',
            rungrid__pb2.Request.SerializeToString,
            rungrid__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailAttempt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rungrid.v1.WorkerService/FailAttempt',
            rungrid__pb2.Request.SerializeToString,
            rungrid__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rungrid.v1.WorkerService/ReleaseWorker',
            rungrid__pb2.Request.SerializeToString,
            rungrid__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
